### ISSUE TITLE
Code may mismatch with the formula in the paper

### ISSUE THREAD

**Issue by moonboy12138** [ShadowXZT/DOFA-pytorch#4]
There appears to be a discrepancy between the code and the formula presented in the paper. Specifically, lines 61-63 of [this file](https://github.com/ShadowXZT/DOFA-pytorch/blob/master/wave_dynamic_layer.py) concatenate the variables as `Concat(Qw, Vλ', Qb)`, which seems to contradict formula (7) on Page 15 of the [paper](https://arxiv.org/abs/2403.15356), where it specifies `Concat(Vλ', Qw, Qb)`. Is this a misunderstanding, or is there an actual mismatch? If it is a mismatch, could it potentially affect the model's performance?

**Comment by ShadowXZT** [comment]
Thanks for pointing this out! 
We noticed this and are in progress updating the Arixv manuscript as well as adding more experiments. 
The code is correct, and the paper will be updated very soon.

If you have further questions, feel free to reopen this issue.
